name = input("Enter your name: ")
surname = input("Enter your surname: ")
age = input("Enter your age: ")
number1 = input("Enter the first number: ")
number2 = input("Enter the second number: ")

print (type(name))
print (type(surname))
print (type(age))
print (type(number1))
print (type(number2))
